### ISSUE TITLE
EFS Mounts not auto mounting

### ISSUE THREAD

**Issue by rlhadsel** [Esri/arcgis-gitops#105]
The EFS mounts used by the arcgis server and arcgis data store as part of the arcgis-enterprise-linux deployment should automatically mount the efs file share following EC2 restarts. After stopping my EC2 instances friday and turning them back on Monday, I had to manually mount the /mnt/efs directory to my primary and standby machines in order for the environment to function correctly. I initially found this problem because of an error with webgisdr import not being able to reach the fileshare:

![image](https://github.com/user-attachments/assets/a6703c18-013f-47dc-ab9e-8d934aff37bb)

After doing some research on the topic, it appears there may be options via modifying the fstab file to include the _netdev option, suggested here: https://repost.aws/knowledge-center/efs-fix-auto-mount-on-reboot-ec2. It is further defined here by Amazon and falls in-line with Amazon's recommended options to include with NFS mounts: https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-nfs-mount-settings.html#:~:text=_netdev%20%E2%80%93%20When%20present%20in%20%2Fetc,your%20%2Fetc%2Ffstab%20file.

Here are a few screenshots of my workaround to get ArcGIS Server back up and running:
- EFS wasn't mounted. Checked /etc/fstab to see if it was listed; found it wasn't in this file:

![image](https://github.com/user-attachments/assets/c828e576-52bd-4eec-9651-eab43beb22b0)

- Mounted EFS using command from SSM document "arcgis-enterprise-nfs-mount"
- Verified the mount was visible and I could see the ArcGIS Server and ArcGIS Data Store directories that are stored in the EFS filesystem

![image](https://github.com/user-attachments/assets/8f67ad75-9bef-4f86-bfc2-027972305d31)

**Comment by pbobov** [comment]
This fix:
1. Installs amazon-efs-utils package on AMIs in arcgis-server-linux-aws-image and arcgis-enterprise-base-linux-aws-image workflows.
2. Changes arcgis-server-linux-aws-infrastructure workflow to use new arcgis.common.efs_mount Ansible playbook instead of an SSM document. (That also removes dependency of arcgis-server-linux template on Chef-specific resources created by site-automation-chef-aws workflow. See #94).
3. Renames SSM document "nfs-mount-*" to "efs-mount-*", changes input parameter FileSystemDNS to FileSystemId, makes the SSM document use "efs" mount type supported by amazon-efs-utils package, and adds the EFS mounts to /etc/fstab file.
4. Changes arcgis-enterprise-base-linux-aws-infrastructure workflow to use new  "efs-mount-*" SSM document.
